/* Shared, dependency-free domain logic. */
(function(root){
const FIELDS={Titre:'Intitulé de la formation',ID_notice:'ID notice / service Noticia',ID_session:'ID session Noticia',Reference_EAFC:'Référence EAFC / SOFIA',Organisation:'Organisme',Atelier:'Atelier',Cadre:'Cadre de la formation',Commanditaire:'Commanditaire',Financeur:'Financeur',Formateurs:'Formateurs',Gestionnaire:'Gestionnaire',Date_debut:'Date de début',Date_fin:'Date de fin',Horaires:'Horaires / créneaux',Duree:'Durée pédagogique (heures)',Lieu:'Lieu / accès',Public:'Public visé',Prerequis:'Prérequis',Besoins:'Contexte et analyse des besoins',Contenu:'Contenu',Methodes:'Méthodes pédagogiques',Accompagnement:'Accompagnement technique et pédagogique',Accessibilite:'Accessibilité / contact dédié',Contact:'Contact organisation',Lien_dossier:'Lien du dossier SharePoint',Notes:'Notes internes'};
const SCHEMA={Q_Sessions:Object.keys(FIELDS).map(id=>({id,type:id==='Duree'?'Numeric':'Text'})),Q_Objectifs:[['Session','Ref:Q_Sessions'],['Ordre','Numeric'],['Objectif','Text'],['Evaluation','Text']].map(([id,type])=>({id,type})),Q_Suivi:[['Session','Ref:Q_Sessions'],...['Code','Etape','Libelle','Indicateurs','Statut','Echeance','Responsable','Lien','Note','Controle_par','Modifie_le'].map(id=>[id,'Text'])].map(([id,type])=>({id,type})),Q_Journal:['Session','Action','Objet','Detail','Date'].map(id=>({id,type:id==='Session'?'Ref:Q_Sessions':'Text'}))};
const TASKS=[
['besoins','1. Analyse','Analyse du besoin et échanges commanditaire / EAFC','4'],['proposition','1. Analyse','Objectifs et proposition validés','4, 5'],['contrat','2. Contractualisation','Cadre contractuel applicable et pièces signées','4'],['notice','3. Ingénierie','Notice et session Noticia identifiées','1, 5'],['programme','3. Ingénierie','Programme communiqué aux stagiaires','1, 9'],['conducteur','3. Ingénierie','Conducteur initial daté et versionné','6'],['positionnement','3. Ingénierie','Positionnement nominatif recueilli et analysé','8'],['prerequis','3. Ingénierie','Prérequis vérifiés si nécessaires','8'],['references','3. Ingénierie','CV, moyens, ressources et accessibilité','17, 18, 19, 21, 26'],['accueil','4. Déploiement','Informations d’accueil / convocation transmises','9'],['emargement','4. Déploiement','Émargements et présences vérifiés','12'],['productions','4. Déploiement','Productions attribuées aux participants','10, 11'],['adaptation','4. Déploiement','Conducteur adapté / réalisé et remédiations','10'],['acquis','5. Évaluation','Acquis évalués par participant et par objectif','11'],['chaud','5. Évaluation','Satisfaction à chaud : recueil et résultats','30'],['froid','5. Évaluation','Satisfaction à froid : suivi à trois mois','30'],['attestations','6. Bilan','Attestations / certificats et mise à disposition','12'],['formateur','6. Bilan','Bilan du formateur','30'],['commanditaire','6. Bilan','Bilan commanditaire / financeur','30'],['amelioration','6. Bilan','Incidents, réclamations et actions d’amélioration','31, 32']];
const STATUS=['À faire','En cours','À vérifier','Vérifié','Non applicable'];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rows=t=>(t.id||[]).map((id,i)=>Object.fromEntries(Object.entries(t).map(([k,v])=>[k,v[i]])));
function validDate(s){return !s||(/^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s+'T00:00:00Z'))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s);}
function addMonths(s,n){if(!s||!validDate(s))return '';const [y,m,d]=s.split('-').map(Number);const end=new Date(Date.UTC(y,m-1+n+1,0)).getUTCDate();return new Date(Date.UTC(y,m-1+n,Math.min(d,end))).toISOString().slice(0,10);}
function today(){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Paris'}).format(new Date());}
function safeURL(s){if(!s)return '';try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
function validateSession(s){if(!String(s.Titre||'').trim())throw Error('Le titre est obligatoire.');for(const k of ['Date_debut','Date_fin'])if(!validDate(s[k]))throw Error('Date invalide : utiliser AAAA-MM-JJ.');if(s.Date_fin&&s.Date_debut&&s.Date_fin<s.Date_debut)throw Error('La fin précède le début.');if(s.Duree!==''&&s.Duree!=null&&(!Number.isFinite(Number(s.Duree))||Number(s.Duree)<0))throw Error('La durée doit être un nombre positif ou nul.');if(s.Lien_dossier&&!safeURL(s.Lien_dossier))throw Error('Le lien du dossier doit commencer par https:// ou http://.');}
function validateTask(t){if(!STATUS.includes(t.Statut))throw Error('Statut inconnu.');if(!validDate(t.Echeance))throw Error('Échéance invalide.');if(t.Lien&&!safeURL(t.Lien))throw Error('Lien de preuve invalide.');if(t.Statut==='Vérifié'&&(!t.Controle_par?.trim()||!(t.Lien?.trim()||t.Note?.trim())))throw Error('Pour vérifier : indiquer le contrôleur et un lien ou une description de la preuve.');if(t.Statut==='Non applicable'&&(!t.Note?.trim()||!t.Controle_par?.trim()))throw Error('Justifier la non-applicabilité et indiquer qui la valide.');}
function progress(tasks,date=today()){const scoped=tasks.filter(t=>t.Statut!=='Non applicable');const due=scoped.filter(t=>!t.Echeance||t.Echeance<=date);const done=due.filter(t=>t.Statut==='Vérifié').length;return {done,total:due.length,percent:due.length?Math.round(100*done/due.length):null,future:scoped.length-due.length,late:due.filter(t=>t.Echeance&&t.Echeance<date&&t.Statut!=='Vérifié').length};}
function parseCSV(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/)[0];const sep=(first.match(/;/g)||[]).length>(first.match(/,/g)||[]).length?';':',';const result=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===sep&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))result.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV invalide : guillemet non fermé.');row.push(cell);if(row.some(x=>x.trim()))result.push(row);if(result.length<2)throw Error('Le CSV doit contenir un en-tête et au moins une ligne.');if(new Set(result[0]).size!==result[0].length)throw Error('Les en-têtes CSV doivent être uniques.');if(result.some(r=>r.length!==result[0].length))throw Error('Le nombre de colonnes varie selon les lignes.');if(result.length>1001)throw Error('Importer au maximum 1 000 sessions à la fois.');return {headers:result[0],data:result.slice(1)};}
const cell=v=>'"'+String(v??'').replace(/^[=+\-@\t\r]/,"' $&").replace(/"/g,'""')+'"';
const csv=(headers,data)=>'\uFEFF'+[headers,...data].map(r=>r.map(cell).join(';')).join('\r\n');
root.QCore={FIELDS,SCHEMA,TASKS,STATUS,esc,rows,validDate,addMonths,today,safeURL,validateSession,validateTask,progress,parseCSV,csv};if(typeof module!=='undefined')module.exports=root.QCore;
})(typeof window!=='undefined'?window:globalThis);
